changelog:
  categories:
    - title: Features
      labels:
        - feature
    - title: Fixes
      labels:
        - bug
        - fix
    - title: Documentation
      labels:
        - docs
    - title: Tooling
      labels:
        - tooling
    - title: Other Changes
      labels:
        - "*"
